syntax enable
set number
set encoding=utf-8
set fileencoding=utf-8
set expandtab
set tabstop=2
set shiftwidth=2
set mouse=a
set clipboard+=unnamedplus
set cursorline
set autoindent
set smartindent
set termguicolors
set showtabline=2
