local alpha = require('alpha')

local dashboard = require("alpha.themes.dashboard")

-- Generated by figlet -f larry3d welcome
-- dashboard.section.header.val = {
--   [[                   ___                                        ]],
--   [[                  /\_ \                                       ]],
--   [[ __  __  __     __\//\ \     ___    ___     ___ ___      __   ]],
--   [[/\ \/\ \/\ \  /'__`\\ \ \   /'___\ / __`\ /' __` __`\  /'__`\ ]],
--   [[\ \ \_/ \_/ \/\  __/ \_\ \_/\ \__//\ \L\ \/\ \/\ \/\ \/\  __/ ]],
--   [[ \ \___x___/'\ \____\/\____\ \____\ \____/\ \_\ \_\ \_\ \____\]],
--   [[  \/__//__/   \/____/\/____/\/____/\/___/  \/_/\/_/\/_/\/____/]],
--   [[                                                              ]],
-- }

dashboard.section.buttons.val = {
  dashboard.button("e", "  New file", "<cmd>ene<CR>"),
  dashboard.button("SPC f f", "  Find file"),
  dashboard.button("SPC f g", "󰍉  Live grep"),
  dashboard.button("SPC f r", "  Recent files"),
  dashboard.button("SPC f p", "  Find project"),
  dashboard.button("c", "  Configuration", ":e $MYVIMRC<CR>"),
  dashboard.button("u", "  Update plugins", "<cmd>PackerSync<CR>"),
  dashboard.button("q", "󰗼  Quit", ":qa<CR>"),
}

local function footer()
  return "meronogbai.me"
end

dashboard.section.footer.val = footer()

dashboard.section.footer.opts.hl = "Type"
dashboard.section.header.opts.hl = "Include"
dashboard.section.buttons.opts.hl = "Keyword"

dashboard.opts.opts.noautocmd = true
alpha.setup(dashboard.opts)
